"""Trusted, code-owned business-rules handlers (P4.3).

These are the deterministic functions the isolated runner executes inside the
container image. They are **trusted** — authored and reviewed here, never
generated by a model and never derived from a package manifest. A package only
*names* a handler (from the allowlist in :mod:`hrca.app_package`); it cannot
supply handler code.

The handlers are pure and deterministic: no filesystem, network, credential or
command access. They return ``(result, error)`` where exactly one is ``None``;
``error`` is a bounded reason token (never interpolating caller content).
Money is computed with :class:`decimal.Decimal` and rounded half-up to two
decimal places, and emitted as fixed two-decimal strings so the exact value is
preserved across the JSON runner boundary.

This module is imported by the in-image ``runner_main`` (see
``packaging/runner``) and by tests — never by the desktop client or the
deterministic boundary, and never on the host as a fallback for package
execution.
"""

from __future__ import annotations

from decimal import Decimal, InvalidOperation, ROUND_HALF_UP
from typing import Any, Dict, Optional, Tuple

_TWO = Decimal("0.01")
_MEMBER_DISCOUNT_RATE = Decimal("0.05")
_SHIPPING_THRESHOLD = Decimal("100")
_SHIPPING_FEE = Decimal("10")
_REGIONAL_FEES = {
    "west": Decimal("0"),
    "north": Decimal("5"),
    "south": Decimal("3"),
    "east": Decimal("8"),
}
_REGIONS = frozenset(_REGIONAL_FEES)

# Bounded error reasons (fixed tokens; never interpolate caller content).
REASON_MISSING = "missing required field"
REASON_SUBTOTAL = "subtotal must be non-negative"
REASON_MEMBER = "member must be a boolean"
REASON_REGION = "region is not supported"


def _money_str(value: Decimal) -> str:
    """Return ``value`` rounded half-up to two decimals as a fixed string."""
    return str(value.quantize(_TWO, rounding=ROUND_HALF_UP))


def _coerce_subtotal(value: Any) -> Optional[Decimal]:
    if isinstance(value, bool):
        return None
    if isinstance(value, int):
        return Decimal(value)
    if isinstance(value, float):
        if value != value or value in (float("inf"), float("-inf")):
            return None
        return Decimal(str(value))
    if isinstance(value, str):
        try:
            return Decimal(value)
        except InvalidOperation:
            return None
    return None


def quotation_rules_evaluate(form: Dict[str, Any]) -> Tuple[Optional[Dict[str, str]], Optional[str]]:
    """Evaluate the quotation-rules package for one validated ``form``.

    Rules (hand-written, deterministic):

    * ``member`` gets a 5% discount (rounded half-up to two decimals);
    * shipping is free at or above a 100.00 post-discount subtotal, else 10.00;
    * a per-region fee applies (west 0, north 5, south 3, east 8);
    * the subtotal must be non-negative and all required fields present;
    * every money value is rounded half-up to two decimal places.

    Returns ``(result, error)``; on success ``error`` is ``None`` and ``result``
    maps each result field to a fixed two-decimal string.
    """
    if not isinstance(form, dict):
        return None, REASON_MISSING
    if "subtotal" not in form:
        return None, REASON_MISSING
    if "member" not in form:
        return None, REASON_MISSING
    if "region" not in form:
        return None, REASON_MISSING

    subtotal = _coerce_subtotal(form["subtotal"])
    if subtotal is None:
        return None, REASON_SUBTOTAL
    if subtotal < 0:
        return None, REASON_SUBTOTAL

    member = form["member"]
    if not isinstance(member, bool):
        return None, REASON_MEMBER

    region = form["region"]
    if region not in _REGIONS:
        return None, REASON_REGION

    discount = subtotal * _MEMBER_DISCOUNT_RATE if member else Decimal("0")
    discount = discount.quantize(_TWO, rounding=ROUND_HALF_UP)
    base = subtotal - discount
    shipping_fee = Decimal("0") if base >= _SHIPPING_THRESHOLD else _SHIPPING_FEE
    regional_fee = _REGIONAL_FEES[region]
    total = subtotal - discount + shipping_fee + regional_fee

    return {
        "discount": _money_str(discount),
        "shipping_fee": _money_str(shipping_fee),
        "regional_fee": _money_str(regional_fee),
        "total": _money_str(total),
    }, None


# The code-owned handler registry the in-image ``runner_main`` resolves a
# package ``handler`` against. Adding a handler is a separate, gated change
# mirrored in :data:`hrca.app_package.ALLOWED_HANDLERS`.
HANDLERS = {
    "quotation_rules.evaluate": quotation_rules_evaluate,
}


def resolve_handler(handler: str):
    """Return the trusted handler for ``handler``, or ``None`` when unknown."""
    return HANDLERS.get(handler)


__all__ = [
    "REASON_MISSING",
    "REASON_SUBTOTAL",
    "REASON_MEMBER",
    "REASON_REGION",
    "quotation_rules_evaluate",
    "HANDLERS",
    "resolve_handler",
]
