"""Trusted, code-owned business-rules handlers (P4.3).

These are the deterministic functions the isolated runner executes inside the
container image. They are **trusted** — authored and reviewed here, never
generated by a model and never derived from a package manifest. A package only
*names* a handler (from the allowlist in :mod:`hrca.app_package`); it cannot
supply handler code.

The handlers are pure and deterministic: no filesystem, network, credential or
command access. They return ``(result, error)`` where exactly one is ``None``;
``error`` is a bounded reason token (never interpolating caller content).
Money is computed with :class:`decimal.Decimal` and rounded half-up to two
decimal places, and emitted as fixed two-decimal strings so the exact value is
preserved across the JSON runner boundary.

This module is imported by the in-image ``runner_main`` (see
``packaging/runner``) and by tests — never by the desktop client or the
deterministic boundary, and never on the host as a fallback for package
execution.
"""

from __future__ import annotations

from decimal import Decimal, InvalidOperation, ROUND_HALF_UP
from typing import Any, Dict, Optional, Tuple

_TWO = Decimal("0.01")
_MEMBER_DISCOUNT_RATE = Decimal("0.05")
_SHIPPING_THRESHOLD = Decimal("100")
_SHIPPING_FEE = Decimal("10")
_REGIONAL_FEES = {
    "west": Decimal("0"),
    "north": Decimal("5"),
    "south": Decimal("3"),
    "east": Decimal("8"),
}
_REGIONS = frozenset(_REGIONAL_FEES)

# A second hand-authored, benign rule variant (P4.7). It is reviewed here, never
# generated or document-interpreted: a 3% member discount, free shipping at or
# above a 150.00 threshold, a 12.00 shipping fee, and a shifted per-region fee.
_ALT_MEMBER_DISCOUNT_RATE = Decimal("0.03")
_ALT_SHIPPING_THRESHOLD = Decimal("150")
_ALT_SHIPPING_FEE = Decimal("12")
_ALT_REGIONAL_FEES = {
    "west": Decimal("1"),
    "north": Decimal("6"),
    "south": Decimal("4"),
    "east": Decimal("9"),
}

# Late-return-fee family (P4.7a, hand-authored). A fixed 3-per-day rate capped at
# a default 30.00; only the cap is a code-owned parameter a rule delta may change.
_LATE_RETURN_DAILY_RATE = Decimal("3")
_LATE_RETURN_DEFAULT_CAP = Decimal("30")

# Bounded reasons for the late-return-fee handler.
REASON_DAYS = "days_late must be a non-negative integer"

# Bounded error reasons (fixed tokens; never interpolate caller content).
REASON_MISSING = "missing required field"
REASON_SUBTOTAL = "subtotal must be non-negative"
REASON_MEMBER = "member must be a boolean"
REASON_REGION = "region is not supported"


def _money_str(value: Decimal) -> str:
    """Return ``value`` rounded half-up to two decimals as a fixed string."""
    return str(value.quantize(_TWO, rounding=ROUND_HALF_UP))


def _coerce_subtotal(value: Any) -> Optional[Decimal]:
    if isinstance(value, bool):
        return None
    if isinstance(value, int):
        return Decimal(value)
    if isinstance(value, float):
        if value != value or value in (float("inf"), float("-inf")):
            return None
        return Decimal(str(value))
    if isinstance(value, str):
        try:
            return Decimal(value)
        except InvalidOperation:
            return None
    return None


def _parameter_decimal(parameters: Any, key: str, default: Decimal) -> Decimal:
    """Return the code-owned parameter ``key`` as a :class:`Decimal`, or ``default``.

    ``parameters`` is the resolved, already-validated delta parameter mapping (a
    dict of decimal strings); it is trusted input from the code-owned resolver,
    never raw candidate text.
    """
    if isinstance(parameters, dict) and key in parameters:
        value = _coerce_subtotal(parameters[key])
        if value is not None:
            return value
    return default


def quotation_rules_evaluate(
    form: Dict[str, Any], parameters: Optional[Dict[str, Any]] = None
) -> Tuple[Optional[Dict[str, str]], Optional[str]]:
    """Evaluate the quotation-rules package for one validated ``form``.

    Rules (hand-written, deterministic):

    * ``member`` gets a 5% discount by default; the code-owned
      ``member_discount_rate`` parameter (a rule delta) may change it;
    * shipping is free at or above a 100.00 post-discount subtotal, else 10.00;
    * a per-region fee applies (west 0, north 5, south 3, east 8);
    * the subtotal must be non-negative and all required fields present;
    * every money value is rounded half-up to two decimal places.

    Returns ``(result, error)``; on success ``error`` is ``None`` and ``result``
    maps each result field to a fixed two-decimal string.
    """
    if not isinstance(form, dict):
        return None, REASON_MISSING
    for key in ("subtotal", "member", "region"):
        if key not in form:
            return None, REASON_MISSING

    subtotal = _coerce_subtotal(form["subtotal"])
    if subtotal is None or subtotal < 0:
        return None, REASON_SUBTOTAL

    member = form["member"]
    if not isinstance(member, bool):
        return None, REASON_MEMBER

    region = form["region"]
    if region not in _REGIONS:
        return None, REASON_REGION

    discount_rate = _parameter_decimal(parameters, "member_discount_rate", _MEMBER_DISCOUNT_RATE)
    discount = subtotal * discount_rate if member else Decimal("0")
    discount = discount.quantize(_TWO, rounding=ROUND_HALF_UP)
    base = subtotal - discount
    shipping_fee = Decimal("0") if base >= _SHIPPING_THRESHOLD else _SHIPPING_FEE
    regional_fee = _REGIONAL_FEES[region]
    total = subtotal - discount + shipping_fee + regional_fee

    return {
        "discount": _money_str(discount),
        "shipping_fee": _money_str(shipping_fee),
        "regional_fee": _money_str(regional_fee),
        "total": _money_str(total),
    }, None


def quotation_rules_alt_evaluate(
    form: Dict[str, Any], parameters: Optional[Dict[str, Any]] = None
) -> Tuple[Optional[Dict[str, str]], Optional[str]]:
    """Evaluate the alternative quotation-rules variant (P4.7, hand-authored).

    ``parameters`` is accepted for parity with the delta-parameterized handlers
    and ignored here (this variant has no changeable parameter).

    Rules differ from :func:`quotation_rules_evaluate` only by their reviewed
    constants: a 3% member discount, free shipping at or above 150.00 (else
    12.00), and a shifted per-region fee (west 1, north 6, south 4, east 9).
    The structure, validation and half-up rounding are identical.
    """
    if not isinstance(form, dict):
        return None, REASON_MISSING
    for key in ("subtotal", "member", "region"):
        if key not in form:
            return None, REASON_MISSING

    subtotal = _coerce_subtotal(form["subtotal"])
    if subtotal is None or subtotal < 0:
        return None, REASON_SUBTOTAL

    member = form["member"]
    if not isinstance(member, bool):
        return None, REASON_MEMBER

    region = form["region"]
    if region not in _ALT_REGIONAL_FEES:
        return None, REASON_REGION

    discount = subtotal * _ALT_MEMBER_DISCOUNT_RATE if member else Decimal("0")
    discount = discount.quantize(_TWO, rounding=ROUND_HALF_UP)
    base = subtotal - discount
    shipping_fee = Decimal("0") if base >= _ALT_SHIPPING_THRESHOLD else _ALT_SHIPPING_FEE
    regional_fee = _ALT_REGIONAL_FEES[region]
    total = subtotal - discount + shipping_fee + regional_fee

    return {
        "discount": _money_str(discount),
        "shipping_fee": _money_str(shipping_fee),
        "regional_fee": _money_str(regional_fee),
        "total": _money_str(total),
    }, None


def late_return_fee_evaluate(
    form: Dict[str, Any], parameters: Optional[Dict[str, Any]] = None
) -> Tuple[Optional[Dict[str, str]], Optional[str]]:
    """Evaluate the late-return-fee package for one validated ``form`` (P4.7a).

    Rules (hand-written, deterministic): a 3-per-day late fee capped at 30.00 by
    default; the code-owned ``cap`` parameter (a rule delta) may change the cap.
    ``days_late`` must be a non-negative integer.
    """
    if not isinstance(form, dict) or "days_late" not in form:
        return None, REASON_MISSING
    days = form["days_late"]
    if isinstance(days, bool) or not isinstance(days, int):
        return None, REASON_DAYS
    if days < 0:
        return None, REASON_DAYS

    cap = _parameter_decimal(parameters, "cap", _LATE_RETURN_DEFAULT_CAP)
    fee = min(Decimal(days) * _LATE_RETURN_DAILY_RATE, cap)
    return {"fee": _money_str(fee)}, None


# The code-owned handler registry the in-image ``runner_main`` resolves a
# package ``handler`` against. Adding a handler is a separate, gated change
# mirrored in :data:`hrca.app_package.ALLOWED_HANDLERS`.
HANDLERS = {
    "quotation_rules.evaluate": quotation_rules_evaluate,
    "quotation_rules_alt.evaluate": quotation_rules_alt_evaluate,
    "late_return_fee.evaluate": late_return_fee_evaluate,
}


def resolve_handler(handler: str):
    """Return the trusted handler for ``handler``, or ``None`` when unknown."""
    return HANDLERS.get(handler)


__all__ = [
    "REASON_MISSING",
    "REASON_SUBTOTAL",
    "REASON_MEMBER",
    "REASON_REGION",
    "REASON_DAYS",
    "quotation_rules_evaluate",
    "quotation_rules_alt_evaluate",
    "late_return_fee_evaluate",
    "HANDLERS",
    "resolve_handler",
]
